Mar-26 10:14:37.953 [main] DEBUG nextflow.cli.Launcher - $> nextflow run disambiguate.nf -resume -c exome.config /
Mar-26 10:14:38.041 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.10.0
Mar-26 10:14:38.062 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/ubuntu/.nextflow/plugins; core-plugins: nf-amazon@2.1.4,nf-azure@1.3.2,nf-cloudcache@0.3.0,nf-codecommit@0.1.5,nf-console@1.0.6,nf-ga4gh@1.1.0,nf-google@1.8.3,nf-tower@1.6.3,nf-wave@1.0.0
Mar-26 10:14:38.073 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Mar-26 10:14:38.074 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Mar-26 10:14:38.077 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Mar-26 10:14:38.088 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Mar-26 10:14:38.110 [main] DEBUG nextflow.config.ConfigBuilder - User config file: /data/local/MD_project/scripts/pipelines/exome/02_disambiguate_test/exome.config
Mar-26 10:14:38.111 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /data/local/MD_project/scripts/pipelines/exome/02_disambiguate_test/exome.config
Mar-26 10:14:38.133 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Mar-26 10:14:38.667 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 by global default
Mar-26 10:14:38.685 [main] INFO  nextflow.cli.CmdRun - Launching `disambiguate.nf` [determined_mayer] DSL2 - revision: 6938987ab5
Mar-26 10:14:38.685 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Mar-26 10:14:38.686 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Mar-26 10:14:38.695 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /home/ubuntu/.nextflow/secrets/store.json
Mar-26 10:14:38.698 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@5a8c93] - activable => nextflow.secret.LocalSecretsProvider@5a8c93
Mar-26 10:14:38.760 [main] DEBUG nextflow.Session - Session UUID: 5838b6bd-5c1e-41ce-b370-3283623ba5ad
Mar-26 10:14:38.760 [main] DEBUG nextflow.Session - Run name: determined_mayer
Mar-26 10:14:38.761 [main] DEBUG nextflow.Session - Executor pool size: 64
Mar-26 10:14:38.769 [main] DEBUG nextflow.file.FilePorter - File porter settings maxRetries=3; maxTransfers=50; pollTimeout=null
Mar-26 10:14:38.773 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=192; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Mar-26 10:14:38.802 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 23.10.0 build 5889
  Created: 15-10-2023 15:07 UTC 
  System: Linux 5.4.0-169-generic
  Runtime: Groovy 3.0.19 on OpenJDK 64-Bit Server VM 11.0.13+7-b1751.21
  Encoding: UTF-8 (UTF-8)
  Process: 1540967@instance-1 [127.0.1.1]
  CPUs: 64 - Mem: 251.7 GB (2.1 GB) - Swap: 0 (0)
Mar-26 10:14:38.830 [main] DEBUG nextflow.Session - Work-dir: /data/local/MD_project/scripts/pipelines/exome/02_disambiguate_test/work [ext2/ext3]
Mar-26 10:14:38.830 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /data/local/MD_project/scripts/pipelines/exome/02_disambiguate_test/bin
Mar-26 10:14:38.873 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Mar-26 10:14:38.884 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Mar-26 10:14:38.904 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Mar-26 10:14:38.916 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 65; maxThreads: 1000
Mar-26 10:14:40.177 [main] DEBUG nextflow.Session - Session start
Mar-26 10:14:40.625 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Mar-26 10:14:40.783 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Mar-26 10:14:40.784 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Mar-26 10:14:40.789 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Mar-26 10:14:40.795 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=64; memory=251.7 GB; capacity=64; pollInterval=100ms; dumpInterval=5m
Mar-26 10:14:40.797 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Mar-26 10:14:40.867 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: bbsplit_batch, test_rename, bbsplit, save_results
Mar-26 10:14:40.868 [main] DEBUG nextflow.Session - Igniting dataflow network (2)
Mar-26 10:14:40.873 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > bbsplit_batch
Mar-26 10:14:40.873 [PathVisitor-1] DEBUG nextflow.file.PathVisitor - files for syntax: glob; folder: /home/ubuntu/data/local/MD_project/data/exome/processed/01_trimmed_umis/; pattern: *_R{1,2}_*.fastq.gz; options: [:]
Mar-26 10:14:40.875 [main] DEBUG nextflow.script.ScriptRunner - Parsed script files:
  Script_16338561fb51718a: /data/local/MD_project/scripts/pipelines/exome/02_disambiguate_test/disambiguate.nf
Mar-26 10:14:40.876 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination 
Mar-26 10:14:40.876 [main] DEBUG nextflow.Session - Session await
Mar-26 10:14:41.389 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Mar-26 10:14:41.391 [Task submitter] INFO  nextflow.Session - [74/528f55] Submitted process > bbsplit_batch (36)
Mar-26 10:14:41.398 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Mar-26 10:14:41.399 [Task submitter] INFO  nextflow.Session - [a4/212bb0] Submitted process > bbsplit_batch (24)
Mar-26 10:14:58.626 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 36; name: bbsplit_batch (36); status: COMPLETED; exit: 1; error: -; workDir: /data/local/MD_project/scripts/pipelines/exome/02_disambiguate_test/work/74/528f5595c48c19cb212ee6bd586621]
Mar-26 10:14:58.630 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Mar-26 10:14:58.630 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=bbsplit_batch (36); work-dir=/data/local/MD_project/scripts/pipelines/exome/02_disambiguate_test/work/74/528f5595c48c19cb212ee6bd586621
  error [nextflow.exception.ProcessFailedException]: Process `bbsplit_batch (36)` terminated with an error exit status (1)
Mar-26 10:14:58.631 [Task submitter] INFO  nextflow.Session - [c7/7290ba] Submitted process > bbsplit_batch (22)
Mar-26 10:14:58.677 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'bbsplit_batch (36)'

Caused by:
  Process `bbsplit_batch (36)` terminated with an error exit status (1)

Command executed:

  rename_1=$(basename $(python3 /home/ubuntu/data/local/MD_project/scripts/pipelines/exome/helper_scripts/return_rename.py 16-PDX_S1_L001_R1_001.1710874524654_Cut_0.fastq.gz) .fastq.gz)
  rename_2=$(basename $(python3 /home/ubuntu/data/local/MD_project/scripts/pipelines/exome/helper_scripts/return_rename.py 16-PDX_S1_L001_R2_001.1710874524654_Cut_0.fastq.gz) .fastq.gz)
  batch=$(python3 /home/ubuntu/data/local/MD_project/scripts/pipelines/exome/helper_scripts/return_batch.py 16-PDX_S1_L001_R1_001.1710874524654_Cut_0.fastq.gz)
  
  
  if  [[ "${batch}" == "374" ]]
  then
  echo 16-PDX_S1_L001_R1_001.1710874524654_Cut_0.fastq.gz >> ${rename_1}.txt
  
  
  bbsplit.sh -Xmx50g in=16-PDX_S1_L001_R1_001.1710874524654_Cut_0.fastq.gz \
  in2=16-PDX_S1_L001_R2_001.1710874524654_Cut_0.fastq.gz ref=/home/ubuntu/data/local/MD_project/data/reference/human/ncbi_dataset/data/GCF_000001405.40/GCF_000001405.40_GRCh38.p14_genomic.fna,/home/ubuntu/data/local/MD_project/data/reference/reference/mouse/ncbi_dataset/data/GCF_000001635.27/GCF_000001635.27_GRCm39_genomic.fna basename=o%.fastq.gz\
  scafstats=${rename_1}.scafstats.txt refstats=${rename_1}.refstats.txt \
  outu1=${rename_1}_clean1.fastq.gz outu2=${rename_2}_clean2.fastq.gz
  
  fi
  
  touch a.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
      print(return_new_name(args[0]))
    File "/home/ubuntu/data/local/MD_project/scripts/pipelines/exome/helper_scripts/return_rename.py", line 14, in return_new_name
      df=pd.read_csv(rename_table,names=["Patient_ID","Lane","Sample","Read","Batch","Raw_name","New_name","Tumi_name"])
    File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 912, in read_csv
      return _read(filepath_or_buffer, kwds)
    File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 577, in _read
      parser = TextFileReader(filepath_or_buffer, **kwds)
    File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 1407, in __init__
      self._engine = self._make_engine(f, self.engine)
    File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
      self.handles = get_handle(
    File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 859, in get_handle
      handle = open(
  FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/scratch/MD_project/scripts/pipelines/exome/file_rename_tumis_table.csv'
  Traceback (most recent call last):
    File "/home/ubuntu/data/local/MD_project/scripts/pipelines/exome/helper_scripts/return_rename.py", line 32, in <module>
      main(sys.argv[1:])
    File "/home/ubuntu/data/local/MD_project/scripts/pipelines/exome/helper_scripts/return_rename.py", line 27, in main
      print(return_new_name(args[0]))
    File "/home/ubuntu/data/local/MD_project/scripts/pipelines/exome/helper_scripts/return_rename.py", line 14, in return_new_name
      df=pd.read_csv(rename_table,names=["Patient_ID","Lane","Sample","Read","Batch","Raw_name","New_name","Tumi_name"])
    File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 912, in read_csv
      return _read(filepath_or_buffer, kwds)
    File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 577, in _read
      parser = TextFileReader(filepath_or_buffer, **kwds)
    File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 1407, in __init__
      self._engine = self._make_engine(f, self.engine)
    File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
      self.handles = get_handle(
    File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 859, in get_handle
      handle = open(
  FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/scratch/MD_project/scripts/pipelines/exome/file_rename_tumis_table.csv'
  Traceback (most recent call last):
    File "/home/ubuntu/data/local/MD_project/scripts/pipelines/exome/helper_scripts/return_batch.py", line 32, in <module>
      main(sys.argv[1:])
    File "/home/ubuntu/data/local/MD_project/scripts/pipelines/exome/helper_scripts/return_batch.py", line 27, in main
      print(return_batch(args[0]))
    File "/home/ubuntu/data/local/MD_project/scripts/pipelines/exome/helper_scripts/return_batch.py", line 14, in return_batch
      df=pd.read_csv(rename_table,names=["Patient_ID","Lane","Sample","Read","Batch","Raw_name","New_name","Tumi_name"])
    File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 912, in read_csv
      return _read(filepath_or_buffer, kwds)
    File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 577, in _read
      parser = TextFileReader(filepath_or_buffer, **kwds)
    File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 1407, in __init__
      self._engine = self._make_engine(f, self.engine)
    File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
      self.handles = get_handle(
    File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 859, in get_handle
      handle = open(
  FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/scratch/MD_project/scripts/pipelines/exome/file_rename_tumis_table.csv'

Work dir:
  /data/local/MD_project/scripts/pipelines/exome/02_disambiguate_test/work/74/528f5595c48c19cb212ee6bd586621

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
Mar-26 10:14:58.683 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `bbsplit_batch (36)` terminated with an error exit status (1)
Mar-26 10:14:58.695 [main] DEBUG nextflow.Session - Session await > all processes finished
Mar-26 10:14:58.697 [main] DEBUG nextflow.Session - Session await > all barriers passed
Mar-26 10:14:58.697 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local) - terminating tasks monitor poll loop
Mar-26 10:14:58.709 [main] WARN  n.processor.TaskPollingMonitor - Killing running tasks (2)
Mar-26 10:14:58.762 [main] DEBUG n.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=48; submittedCount=1; runningCount=-1; retriesCount=0; abortedCount=2; succeedDuration=0ms; failedDuration=17.2s; cachedDuration=0ms;loadCpus=-1; loadMemory=0; peakRunning=2; peakCpus=2; peakMemory=0; ]
Mar-26 10:14:58.893 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Mar-26 10:14:58.901 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
